site_name: My Docs
site_dir: ..\PathPlanDocsRelease
theme:
  name: material
nav:
  - 'Introduction.md'
  - 'Common.md'
  - 'GetAcc.md'
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - admonition
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - css/style.css
